### ISSUE TITLE
Insert the descriptor to the flow spec

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#195]
As a Flow Manager, I need descriptor (entire datapackage.json) to be present in source-spec sent by CLI

## Acceptance Criteria 

* [x] `inputs` (in source-spec) has descriptor init (see analysis)

## Tasks

* [x] estimate
* [x] update tests
* [x] update `data push`

## Analysis

Current look of source-spec.yaml 
```
meta:
  dataset: single-file
  findability: published
  owner: datahub
  ownerid: datahub
  version: 1
inputs:
- kind: datapackage
  url: datapackage.json
  parameters:
    resource-mapping:
      birthdays: https://rawstore.datahub.io/datahub/data/sample_birthdays.csv
```

Desired look of new source-spec
```
meta:
  dataset: single-file
  findability: published
  owner: datahub
  ownerid: datahub
  version: 1
inputs:
- kind: datapackage
  url: datapackage.json
  parameters:
    resource-mapping:
      birthdays: https://rawstore.datahub.io/datahub/data/sample_birthdays.csv
    descriptor:
      name: single-file
      resources:
        -
          name: birthdays
          path: data/birthdays.csv
          format: csv
          schema:
            fields:
              -
                name: date
                type: date
              -
                name: first_name
                type: string
              -
                name: last_name
                type: string
```
