### ISSUE TITLE
Refactor library to use parseIdentifier and datapackage lib

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#65]
* refactor commands to use parseIdentifier function
* refactor the library to use datapackage-js library for loading/creation
  * e.g., take a look at `data validate url`

```javascript=
  const identifier = utils.parseIdentifier(pkgId)
  let dp = await datapackage.DataPackage.load(identifier.pathPackageJsonUrl)
  // future
  // dp = await datapackage.DataPackage.load(identifier)
  // dp.descriptor.readme = ...
  // dp.descriptor.readmeSnippet = ...
  // dp.descriptor.readmePath = ...
  // utils.getReadme(dataPackage) - afterwards descriptor has README on it ...
```

## Acceptance criteria

* [x] I can run `data info https://github.com/...` and get info about data package in GitHub
* [x] I can run `data info data info http://someurl.com/path/to/datapackage/` and get info about data package in given remote path
* [x] I can run `data info publisher/name` and get info about data package in DataHub
* [x] All above points also apply for `data get` command
* [x] All above points also apply for `data validate` command
* [x] I can run `data info` and get info about data package in cwd
* [x] I can run `data validate` and get info about data package in cwd

## Tasks

* [x] refactor `parseIdentifier` function (see analysis for more details)
* [x] refactor `/lib/get.js`
* [x] refactor `/lib/info.js`
* [x] refactor `/lib/validate.js`
* [ ] ~refactor other modules to use `datapackage-js` library~

## Analysis

```
data info https://github.com/...
data info http://someurl.com/path/to/datapackage/
data info local/path
data info publisher/name

# problem last two are ambiguous!!
# solutions?

# A - introduce dh:// prefix for datahub stuff
data info dh://publisher/name

# B
# data info checks whether local path exists and uses that if present ...
# if local/path exists locally use that o/w try datahub
# Rufus: don't like B at all because of magic ...
data info local/path

# C
# disallow
data info local/path
# only allow doing in current directory ...
data info

---

# similar issues with data get, and validate command

# no issues with purge (dh only), push (not relevant)

# norm is local only

```

```
# only ambiguity is local path and datahub
parseIdentifier(identifier, hint='datahub') {
  out = dpident.parse('abc/xyz')
  // tidy up out to our form e.g. path for url etc
  ...
  
  if (out.local && hint=='datahub') {
    out.type = 'datahub'
    // reparse the identifier as datahub
  }
  
  return out
}
```

https://github.com/datopian/datahub-cli/issues/59

```
github
{
  name:
  owner: github user e.g. /rufuspollock/my-data
  # no trailing slash (url in old spec becomes path)
  path: url or file path to base of dp
  dataPackageJsonPath: url or file path to ....
  type: url | local | datahub | github 
  original: ... 
  version: ...
  resourcePath: ... 
}

# random url
{
  name: last part of path
  owner: null
  # no trailing slash (url in old spec becomes path)
  path: url or file path to base of dp
  dataPackageJsonPath: url or file path to ....
  type: url | local | datahub | github 
  original: ... 
  version: ...
  resourcePath: ... 
}
```
